### ISSUE TITLE
Error running sample code

### ISSUE THREAD

**Issue by XiaomingY** [TomCrypto/Embree.NET#2] opened 2016-09-01 10:10 UTC
Hi, this project is a great help for c# developers. I would like to use Embree in a c# project. However I am having some problems using the sample code. 
_Embree.NET Sample
=================

[+] 64-bit mode.
[+] Building a test scene.
[!] Error: An invalid operation was attempted on an Embree object.

========= STACK TRACE =========

   at Embree.RTC.CheckLastError() in s:\Raytracer\Embree.NET-master\Library\Native.cs:line 92
   at Embree.Scene`1.Commit() in s:\Raytracer\Embree.NET-master\Library\Embree.cs:line 257
   at Sample.Renderer..ctor() in s:\Raytracer\Embree.NET-master\Sample\Program.cs:line 179
   at Sample.Program.Main(String[] args) in s:\Raytracer\Embree.NET-master\Sample\Program.cs:line 325_

Could you help me to figure this out? Thank you.

**Comment by TomCrypto** [comment] 2016-09-01 10:45
What version of Embree are you using? What operating system are you running on?

**Comment by XiaomingY** [comment] 2016-09-01 14:24
Thank you for your reply. I just downloaded everything from Embree.net and build the sample in Visual Studio Express 2013 on Windows 7. There is no error in building Sample.exe Embree.net.dll and Benchmark.exe. Then I have the above error when I run sample.exe.

I also have Embree 2.10 installed but is it related to the error I am having?

**Comment by TomCrypto** [comment] 2016-09-01 20:30
I'll check it out this evening and let you know.

**Comment by TomCrypto** [comment] 2016-09-02 06:50
Are you able to run `Sample.exe verbose` and post the verbose output? I am going to try to replicate on Windows 7 now.

**Comment by XiaomingY** [comment] 2016-09-02 08:58
I just tried Sample.exe verbose:

Embree.NET Sample [VERBOSE]
===========================
Embree Ray Tracing Kernels 2.4.0 (Jan  7 2015)
  Compiler : Intel Compiler 14.0.3
  Platform : Windows (64bit)
  CPU      : SSE SSE2 SSE3 SSSE3 SSE41 SSE42 POPCNT
  Features : intersection_filter bufferstride
general:
  build threads = 0
  verbosity     = 999
triangles:
  accel         = default
  builder       = default
  traverser     = default
  replications  = 2
motion blur triangles:
  accel         = default
  builder       = default
  traverser     = default
hair:
  accel         = default
  builder       = default
  traverser     = default
  replications  = 3
subdivision surfaces:
  accel         = default

[+] 64-bit mode.
[+] Building a test scene.
building BVH4<triangle4> with sse2::BVH4Builder(spatialsplits) ... [DONE]
  dt = 222.949ms, perf = 4.87669 Mprim/s
  primitives = 1087254, vertices = 0, hash= 32558728206381455
  sah = 1.0000, depth = 14
  used = 87.9 MB, perPrimitive = 80.9 B
  alignedNodes = 111890 (86.3% filled) (14.3 MB) (16.3% of total)
  leaves = 274354 (73.6 MB) (83.7% of total)
  vertices = 0 (0.0 MB) (0.0% of total) (75.0% used)
created scene intersector
  accels[0]
    intersector1  = sse41::BVH4Triangle4Intersector1Moeller
    intersector4  = sse42::BVH4Triangle4Intersector4HybridMoellerNoFilter
selected scene intersector
  intersector1  = sse41::BVH4Triangle4Intersector1Moeller
  intersector4  = sse42::BVH4Triangle4Intersector4HybridMoellerNoFilter
Embree: Invalid operation, (static geometries cannot get enabled)
[!] Error: An invalid operation was attempted on an Embree object.

========= STACK TRACE =========

   at Embree.RTC.CheckLastError() in s:\Raytracer\Embree.NET-master\Library\Native.cs:line 92
   at Embree.Scene`1.Commit() in s:\Raytracer\Embree.NET-master\Library\Embree.cs:line 257
   at Sample.Renderer..ctor() in s:\Raytracer\Embree.NET-master\Sample\Program.cs:line 179
   at Sample.Program.Main(String[] args) in s:\Raytracer\Embree.NET-master\Sample\Program.cs:line 325

**Comment by TomCrypto** [comment] 2016-09-02 09:32
Ok, I can reproduce with Embree 2.4. The error is:

    Embree: Invalid operation, (static geometries cannot get enabled)

 It looks like this may actually be a bug in that version of Embree, as the API specifies that static geometries may be enabled or disabled up until you first commit them, which my sample is doing.

> A static scene is created by the rtcDeviceNewScene call with the RTC_SCENE_STATIC flag. **Geometries can only get created, enabled, disabled and modified until the first rtcCommit call**. After the rtcCommit call, each access to any geometry of that static scene is invalid. Geometries that got created inside a static scene can only get deleted by deleting the entire scene.

Please upgrade to a later version of Embree, such as 2.10 (I tested it and it works). If you've got the 2.4 DLL in your system path you might need to do a clean uninstall, or undo whatever you did to install it, to replace it with the newer version. Alternatively just drop the new DLL inside the folder next to the sample.

**Comment by XiaomingY** [comment] 2016-09-02 11:04
Hi Tom, thank you for the quick feed back. Can you tell me how do I use Embree 2.10 for compiling the sample? Right now I just download everything in the repository and build in Visual Studio and it is using Embree 2.4. How do I set reference to Embree 2.10? Thank you.

**Comment by TomCrypto** [comment] 2016-09-02 11:10
You need to find wherever your Embree 2.4 DLL is. The Embree.NET repository doesn't come with the Embree runtime, it just looks for the DLL on your system; you won't be able to change that in Visual Studio, you need to locate your `embree.dll` and update it.

**Comment by XiaomingY** [comment] 2016-09-02 11:34
Thank you for your reply. I guess I do not know how the wrapper works and ask naive questions. I don't know how the wrapper loate the embree.dll. Actually I uninstalled Embree from my computer and rebuild the wrapper and I still have the message (sample verbose):
Embree Ray Tracing Kernels 2.4.0 (Jan 7 2015)
Compiler : Intel Compiler 14.0.3 
Is there a way to reference embree.dll from my computer in the project?

**Comment by TomCrypto** [comment] 2016-09-02 11:44
The wrapper is simply a .NET assembly that calls into the native C/C++ Embree DLL. I don't distribute the native DLL because it just complicates things. I would have to keep track of all Embree versions, for all operating systems, it's much simpler if users can just choose whatever version they want.

The DLL is located using the .NET PInvoke facility, which itself calls into the operating system's DLL resolver. [Click here to see how the system searches for DLLs](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx#search_order_for_desktop_applications).

What I suggest:

 - The quick workaround is to get the Embree 2.10 DLL and place it next to Sample.exe; that should override the 2.4 DLL that's sitting somewhere on your computer. **Note that you should grab the 64-bit `embree.dll` since it seems you're running Embree.NET in x64 mode; make sure to do that or the DLL will silently be ignored!**
 - Otherwise, you can just do a search for `embree.dll` in Windows explorer over the entire computer and it should find it eventually. You will likely find it in your System32 folder. Then you can replace it with the new version.

**Comment by XiaomingY** [comment] 2016-09-02 13:21
Hi Tom, thank you so much for your help. I realized it is using embree.dll from Luxrender installation...Now I have the renders. Thank you!

**Comment by TomCrypto** [comment] 2016-09-02 13:27
You're welcome :) feel free to close the issue whenever you're satisfied everything is working!

**Closed** 2016-09-02 16:00 UTC
